import Head from "next/head";
import { Footer } from "./footer/Footer";
import { MiniCart } from "./mini-cart/MiniCart";
import { Banner } from "./banner/Banner";

export default function Layout({ children }: any) {
  return (
    <>
      <Head>
        <title>Fake Store</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mb-20">
        <Banner />
        <MiniCart />
        {children}
        <Footer />
      </main>
    </>
  );
}
